### ISSUE TITLE
Translations info

### ISSUE THREAD

**Issue by plambros** [zikalify/StoicReading#3]
I've looked both here and in the f-droid page, but I've not been able to find any source or license information for the translated texts. Did I miss it, or should it be added?

**Comment by zikalify** [comment]
Most is from Wikisource, Aurelius meditations was off a website but have made tweaks myself to fix errors and Rufus material was off Google Sites and I contacted author and he believes it's all in public domain. Afaik everything is public domain in the app, I made sure not to add anything explicitly under copyright.

**Comment by zikalify** [comment]
@plambros I'm working on curating a list of sources atm, I'll initially add a credits file into this repository and then work out how to add a button inside the app with my sources. Thanks.
