### ISSUE TITLE
Icon is broken on Android 9

### ISSUE THREAD

**Issue by metbic** [zikalify/StoicReading#8]
In f-droid, stoicreading has this red/orange fireball icon. 
But after installing, a green bg white android head system icon shows up in apps list and on the homescreen.

**Comment by zikalify** [comment]
Ok I'll look into it

**Comment by zikalify** [comment]
> In f-droid, stoicreading has this red/orange fireball icon.
> But after installing, a green bg white android head system icon shows up in apps list and on the homescreen.

I've pushed the fix, look out for 1.0.2 update in F-droid in the next few days.
